SELECT 'MEMBRESIA' AS tabla, COUNT(*) AS cantidad FROM MEMBRESIA
UNION ALL
SELECT 'SUCURSAL', COUNT(*) FROM SUCURSAL
UNION ALL
SELECT 'SOCIO', COUNT(*) FROM SOCIO
UNION ALL
SELECT 'TELEFONO_SOCIO', COUNT(*) FROM TELEFONO_SOCIO
UNION ALL
SELECT 'EMPLEADO', COUNT(*) FROM EMPLEADO
UNION ALL
SELECT 'CERTIFICACION', COUNT(*) FROM CERTIFICACION
UNION ALL
SELECT 'ASIGNACION_EMPLEADO', COUNT(*) FROM ASIGNACION_EMPLEADO
UNION ALL
SELECT 'CLASE', COUNT(*) FROM CLASE
UNION ALL
SELECT 'HORARIO_CLASE', COUNT(*) FROM HORARIO_CLASE
UNION ALL
SELECT 'INSCRIPCION', COUNT(*) FROM INSCRIPCION
UNION ALL
SELECT 'ASISTENCIA', COUNT(*) FROM ASISTENCIA
UNION ALL
SELECT 'SALA', COUNT(*) FROM SALA
UNION ALL
SELECT 'EQUIPO', COUNT(*) FROM EQUIPO
UNION ALL
SELECT 'MANTENIMIENTO', COUNT(*) FROM MANTENIMIENTO
UNION ALL
SELECT 'FACTURA', COUNT(*) FROM FACTURA
UNION ALL
SELECT 'DETALLE_FACTURA', COUNT(*) FROM DETALLE_FACTURA
UNION ALL
SELECT 'PAGO', COUNT(*) FROM PAGO
UNION ALL
SELECT 'RUTINA', COUNT(*) FROM RUTINA
UNION ALL
SELECT 'PROGRESO_FISICO', COUNT(*) FROM PROGRESO_FISICO
UNION ALL
SELECT 'DICTA_EN', COUNT(*) FROM DICTA_EN
UNION ALL
SELECT 'CONTRATACION_MEMBRESIA', COUNT(*) FROM CONTRATACION_MEMBRESIA
ORDER BY tabla;